# Generated by Django 4.0 on 2022-02-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.DateField()),
                ('cours', models.IntegerField()),
                ('individual', models.BooleanField()),
                ('photography', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_api.sections')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students_api.students')),
            ],
        ),
    ]
