# Generated by Django 4.0 on 2022-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='photography',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
