# Generated by Django 4.0 on 2022-03-01 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0002_alter_students_photography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='date',
            new_name='stud_date',
        ),
    ]
