# Generated by Django 4.0 on 2022-03-07 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0003_rename_date_students_stud_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='name',
            new_name='section',
        ),
    ]
