# Generated by Django 4.0 on 2022-03-08 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students_api', '0004_rename_name_sections_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stud_group',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
